version: '3'
services:
  spring-boot-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # Adjust the ports as needed
    depends_on:
      - react-app  # This ensures that the React app container starts first

  react-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8079:8079"  # Adjust the ports as needed
